# frontend/Dockerfile.dev
# ─────────────────────────────────────────────────────
FROM node:22.15.0-alpine3.20

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy full source for hot reloading, etc.
COPY . .

EXPOSE 3000

# Start dev server (with optional hot reload support)
CMD ["npm", "run", "dev"]
